### ISSUE TITLE
aggregate_by_date requires column named "variable"

### ISSUE THREAD

**Issue by mooibroekd** [skgrange/threadr#13]
In order to use the full potential of `aggregate_by_date` (i.e., calculating averages of `wd`) the input dataframe requires a column named `variable`. Using any other column name will fail to calculate the wd correctly.

However, when using the `aggregate_by_date` in combination with the `by` parameter requires the `variable`. But this can also be any other column (i.e., `pollutants`, `species`, `factors`). Is it possible to make this a user defined variable name, so that the checking occurs on that column instead of the hardcoded `variable`?

**Comment by skgrange** [comment]
I am unwilling to change the hardcoded `variable` name at this stage. This function uses two other reserved variables/columns (`date` and `value`) which are also required for the function. Renaming is easy to do these days in a pipeline and requiring these reserved words keeps the usage appropriately constrained which is how this function was designed.
