### ISSUE TITLE
[feature]: expand time_pad to use full range of dates in dataframe (i.e., ignore by)

### ISSUE THREAD

**Issue by mooibroekd** [skgrange/threadr#14]
Hey Stuart,

Is it possible to add a variable to the `time_pad` function to allow padding the time series using the minimum and maximum datetime in a dataframe?

For example, if one would have two sites in a single dataframe with data from 2015 - 2019, but one site started measurements in 2016. How `time_pad` works by default is that one site is padded from 2015 - 2019 and the other from 2016 - 2019. There are cases when having the same periods for each site in a single dataframe makes it easier to automatically generate tables in R.

I think the easiest way would be to introduce `date_start` and `date_end` in the `time_pad_worker` function, with a default setting of `NA` in which case the function falls back into the current behavior.  In the other case the min and max date of the full dataset is passed.

That would require having the `time_pad` function a new variable that signifies if the padding goes by grouping, or not. Anyways, this is just a thought, but it would help me out a lot.

**Comment by skgrange** [comment]
Hello Dennis,
Sure, that has been done. `time_pad` has a new argument called `uniform_padding`. The usage is something like this: 

```
# An example
data_calibration_pad <- time_pad(
  data_calibration, 
  interval = "day", 
  by = c("sensor_id", "variable", "variable_predict", "term"),
  uniform_padding = TRUE
)
```

This new functionality has not seen much scope with edge cases, so please have a test and see if it is behaving as it should and I can make some enhancements when required. Thanks and I hope it helps! 
Stuart.

**Comment by mooibroekd** [comment]
Works like a charm for my application. Thanks!
