### ISSUE TITLE
plot_time_variation only returns single plot

### ISSUE THREAD

**Issue by mooibroekd** [skgrange/threadr#15]
Hi Stuart,

The documentation of `plot_time_variation` suggests that the function returns a list of the four plots. However, only the final plot (created by `cowplot`) is returned. I want to extract a single plot, so a list would be beneficial for this. Is it possible to print the plot (with an option in the function call to ignore the plot) and return the list of plots invisible? This list could also contain the combined plot.

Best,
Dennis

**Comment by skgrange** [comment]
Hello Dennis,
That will not be a problem to address. I am travelling again at the moment, so I will have to take a look when I am back at my workspace again. All the best for the final push of the year and I will push an enhancement when I can. Enjoy!

**Comment by skgrange** [comment]
Hello Dennis,
The change has been pushed. You will now be able to access the individual plots with something like this: 

```
# Plot and assign return
list_plot_time_variation <- plot_time_variation(df)

# Access an individual plot from the list object
list_plot_time_variation$plots_individual$hours
```

Enjoy!
