### ISSUE TITLE
get_remote_file with ftp credentials?

### ISSUE THREAD

**Issue by PurenBITeam** [skgrange/threadr#2]
Hello there,

great package, especially the ftp part.

I saw that the download_ftp_file function gets deprecated.

I tried the get_remote_file function with a combined URL (including the credentials). This way I do not get a connection to FTP with the error message below.

1: In download.file(url = file_remote, destfile = file_local, quiet = !verbose,  :
  InternetOpenUrl failed: 'The server name or address could not be resolved

Do you have any other way for that?

thanks and br

christoph

**Comment by skgrange** [comment]
Hello Christoph. Good to hear things have been useful for you. `get_remote_file` does not allow the use for credentials yet. Did `download_ftp_file` work well for you? If so, I can un-deprecate the function, it just relies on an old code base which may break in the future.

**Comment by PurenBITeam** [comment]
Hello, yes download_ftp_file worked great. Can I help in some way, so the code won't break in the future?
thanks and br

**Comment by skgrange** [comment]
I have un-dueprecated the function for you Christoph. The best thing to do would be to enhance `get_remote_file` to handle ftp credentials. I will put it on the to-do list but for now, use `download_ftp_file`.
